name = "ShadowGraphs"
uuid = "bb16ec3a-7e9e-4bd8-a580-2befe1914c0f"
authors = ["Henrik Wolf <henrik-wolf@freenet.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
